<?php

declare(strict_types=1);

/**
 * BSD 3-Clause License.
 *
 * @copyright (c) 2019, Google Inc.
 *
 * @see https://www.google.com/recaptcha
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once __DIR__.'/../src/autoload.php';
use ReCaptcha\ReCaptcha;

// Register API keys at https://www.google.com/recaptcha/admin
$siteKey = (string) getenv('RECAPTCHA_V3_SITE');
$secret = (string) getenv('RECAPTCHA_V3_SECRET');

// Copy the config.php.dist file to config.php and update it with your keys to run the examples
if (('' === $siteKey || '' === $secret) && is_readable(__DIR__.'/config.php')) {
    /** @var array{v3: array{site: string, secret: string}} $config */
    $config = include __DIR__.'/config.php';
    $siteKey = $config['v3']['site'];
    $secret = $config['v3']['secret'];
}

// Effectively we're providing an API endpoint here that will accept the token, verify it, and return the action / score to the page
// In production, always sanitize and validate the input you retrieve from the request, and hardcode (or allowlist) the expected action server-side.
$baseRecaptcha = new ReCaptcha($secret)
    ->withExpectedHostname(isset($_SERVER['SERVER_NAME']) && is_string($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : '')
    ->withChallengeTimeout(120)
;

$allowedActions = [
    'examples/v3scores' => 0.5,
    'examples/csp' => 0.5,
    'examples/v3immutable' => 0.5,
    'examples/v3strict' => 0.99,
];
$action = isset($_GET['action']) && is_string($_GET['action']) && isset($allowedActions[$_GET['action']])
    ? $_GET['action']
    : 'examples/v3scores';

$token = isset($_GET['token']) && is_string($_GET['token']) ? $_GET['token'] : '';
$remoteAddr = isset($_SERVER['REMOTE_ADDR']) && is_string($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : null;

// Derive a strict verifier first to demonstrate that with*() does not mutate $baseRecaptcha
$strictVerifier = $baseRecaptcha
    ->withExpectedAction('examples/v3strict')
    ->withScoreThreshold(0.99)
;

$verifier = 'examples/v3strict' === $action
    ? $strictVerifier
    : $baseRecaptcha
        ->withExpectedAction($action)
        ->withScoreThreshold($allowedActions[$action])
;

$resp = $verifier->verify($token, $remoteAddr);
header('Content-type:application/json');
echo json_encode($resp);
